/*
 * authors: Dominik Juraszek, Konrad Chmiel,Sebastian Brandys
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;

import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;

import Controller.Controller;

public class ResultsViewPanel extends javax.swing.JPanel {

    private final GraphPanel graphPanel; // graph panel, to show graph
    private final Controller controller; // application controller

    /**
     * Constructor.
     *
     * @param graphPanel
     * @param controller
     */
    public ResultsViewPanel(GraphPanel graphPanel, Controller controller) {
        initComponents();
        this.graphPanel = graphPanel;
        this.controller = controller;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    private void initComponents() {

        iterationPanel = new javax.swing.JPanel();
        iterationSpinner = new javax.swing.JSpinner(new SpinnerNumberModel(0, 0, 0, 1));
        iterationSpinnerLabel = new javax.swing.JLabel();
        showIterationButton = new javax.swing.JButton();

        iterationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Widok grafu w okreœlonej iteracji"));

        iterationSpinnerLabel.setText("Iteracja");

        showIterationButton.setText("Poka¿");
        showIterationButton = createCustomButton("Poka¿");


  
        
        JPanel iter = new JPanel();
        iter.add(iterationSpinnerLabel);
        iter.add(iterationSpinner);
        iter.add(showIterationButton);
        iterationPanel.add(iter);
        

      

        
      
        
        
        this.setLayout(new BoxLayout(this,BoxLayout.Y_AXIS));
        JPanel emptyPanel2 = new JPanel();
        
        this.add(emptyPanel2);
        this.add(iterationPanel);

        
        JPanel emptyPanel = new JPanel();
        
        this.add(emptyPanel);
        Dimension box = new Dimension(350,60);
        Dimension box2 = new Dimension(350,80);

        
        iterationPanel.setMaximumSize(box2);


        
        iterationPanel.setPreferredSize(box2);

        
    }// </editor-fold>//GEN-END:initComponents
    
    public static javax.swing.JButton createCustomButton(String text) {
    	javax.swing.JButton button = new javax.swing.JButton(text);
    	  button.setForeground(Color.WHITE);
    	  button.setBackground(Color.DARK_GRAY);
    	 // button.setBorder(null);
    	  button.setOpaque(true);
    	  button.setText(text);
    	  return button;
    	}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel iterationPanel;
    private javax.swing.JSpinner iterationSpinner;
    private javax.swing.JLabel iterationSpinnerLabel;

    private javax.swing.JButton showIterationButton;
    // End of variables declaration//GEN-END:variables
}
